version: '3'
services:
  web:
    build:
      context: ./html
      dockerfile: DockerFile
    ports:
      - "8080:80"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=first
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Ulebud10-
   # volumes:
   #   - ./html:/var/www/html
   #   - db_data:/var/lib/mysql
    depends_on:
      - db
    networks:
      custom_network:
        ipv4_address: 10.10.0.10
  db:
    image: mariadb
    environment:
      MYSQL_DATABAASE: first
      MYSQL_USER: kali
      MYSQL_PASSWORD: kali
      MYSQL_ROOT_PASSWORD: kali
    volumes:
      - db_data:/var/lib/mysql
    networks:
      custom_network:
        ipv4_address: 10.10.0.11

volumes:
  db_data: {}

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
